apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web # any key-value you want for matching
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: tepkool01/multi-client
          ports:
            - containerPort: 3000